#!/bin/sh
# Wrapper menu script for grim and slurp
# requires: grim, slurp, wl-clipboard, libnotify, xdg-user-dirs, satty, and menu script

set -eu

dir="$(xdg-user-dir PICTURES)/screenshots"
[ -d "$dir" ] || mkdir -p "$dir" || {
	echo "$(basename "$0"): cannot create directory $dir" >&2
	notify-send -u critical -a "$(basename "$0")" "error" "cannot create directory $dir"
	exit 1
}

sel="${1:-$(printf "select\nfullscreen\nselect-copy\nfullscreen-copy\nselect-edit\nfullscreen-edit" | menu)}" || exit 1
out="$dir/$(date "+%Y%m%d-%H%M%S").png"
case "$sel" in
	select)
		g="$(slurp -d)" || exit 1
		grim -g "$g" "$out"
		notify-send -a "$(basename "$0")" "screenshot" "saved to $out"
		;;
	fullscreen)
		grim "$out"
		notify-send -a "$(basename "$0")" "screenshot" "saved to $out"
		;;
	select-copy)
		g="$(slurp -d)" || exit 1
		grim -g "$g" - | wl-copy -t image/png
		notify-send -a "$(basename "$0")" "screenshot" "saved to clipboard"
		;;
	fullscreen-copy)
		grim - | wl-copy -t image/png
		notify-send -a "$(basename "$0")" "screenshot" "saved to clipboard"
		;;
	select-edit)
		g="$(slurp -d)" || exit 1
		grim -g "$g" -t ppm - | satty -f - -o "$out"
		;;
	fullscreen-edit)
		grim -t ppm - | satty -f - -o "$out"
		;;
	*)
		exit 1
		;;
esac
