#!/bin/sh
# Wrapper menu script for grim and slurp
# requires: grim, slurp, wl-clipboard, libnotify, xdg-user-dirs, satty, and menu script

set -eu

export MENU_PROMPT="${MENU_PROMPT:-Screenshot}"

SCREENSHOTS_DIR="${SCREENSHOTS_DIR:-$(xdg-user-dir PICTURES)/screenshots}"
[ -d "$SCREENSHOTS_DIR" ] || mkdir -p "$SCREENSHOTS_DIR" || {
	echo "$(basename "$0"): cannot create directory $SCREENSHOTS_DIR" >&2
	notify-send -u critical -a "$(basename "$0")" "error" "cannot create directory $SCREENSHOTS_DIR"
	exit 1
}

sel="${1:-$(printf " Select\n Fullscreen" | menu slug)}" || exit 1
case "$sel" in
	fullscreen) ;;
	select)
		g="$(slurp -d)" || exit 1
		;;
	*)
		echo "$(basename "$0"): invalid command: $sel" >&2
		exit 1
		;;
esac

sel="${2:-$(printf " Copy\n Save\n Edit" | menu slug)}" || exit 1
case "$sel" in
	copy)
		grim ${g:+-g "$g"} - | wl-copy --type image/png --foreground --trim-newline
		notify-send -a "$(basename "$0")" "screenshot" "saved to clipboard"
		;;
	save)
		out="$SCREENSHOTS_DIR/$(date "+%Y%m%d-%H%M%S").png"
		grim ${g:+-g "$g"} "$out"
		notify-send -a "$(basename "$0")" "screenshot" "saved to $out"
		;;
	edit)
		out="$SCREENSHOTS_DIR/$(date "+%Y%m%d-%H%M%S").png"
		grim ${g:+-g "$g"} -t ppm - | satty -f - -o "$out"
		;;
	*)
		echo "$(basename "$0"): invalid subcommand: $sel" >&2
		exit 1
		;;
esac
