#!/bin/sh
# Wrapper menu script for grim and slurp
# requires: grim, slurp, wl-clipboard, libnotify, xdg-user-dirs, satty, and menu script

set -eu

export MENU_PROMPT="${MENU_PROMPT:-Screenshot}"

dir="$(xdg-user-dir PICTURES)/screenshots"
[ -d "$dir" ] || mkdir -p "$dir" || {
	echo "$(basename "$0"): cannot create directory $dir" >&2
	notify-send -u critical -a "$(basename "$0")" "error" "cannot create directory $dir"
	exit 1
}

sel="${1:-$(printf " Select\n Fullscreen" | menu slug)}" || exit 1
case "$sel" in
	fullscreen)
		;;
	select)
		g="$(slurp -d)" || exit 1
		;;
	*)
		echo "$(basename "$0"): invalid command: $sel" >&2
		exit 1
		;;
esac

sel="${2:-$(printf " Copy\n Save\n Edit" | menu slug)}" || exit 1
case "$sel" in
	copy)
		grim ${g:+-g "$g"} - | wl-copy -t image/png
		notify-send -a "$(basename "$0")" "screenshot" "saved to clipboard"
		;;
	save)
		out="$dir/$(date "+%Y%m%d-%H%M%S").png"
		grim ${g:+-g "$g"} "$out"
		notify-send -a "$(basename "$0")" "screenshot" "saved to $out"
		;;
	edit)
		grim ${g:+-g "$g"} -t ppm - | satty -f - -o "$out"
		;;
	*)
		echo "$(basename "$0"): invalid subcommand: $sel" >&2
		exit 1
		;;
esac
