#!/bin/sh

set -eu

HERE="$(dirname "$(readlink -f "$0")")"
. "$HERE/.config/shell/env"

SETUP_PROGRAMS_DIR="${SETUP_PROGRAMS_DIR:-$HOME/programs}"
SETUP_PKGS_FILE="${SETUP_PKGS_FILE:-$XDG_DATA_HOME/meta/pkgs.txt}"
SETUP_PKGS_FLATPAKS_FILE="${SETUP_PKGS_FLATPAKS_FILE:-$XDG_DATA_HOME/meta/flatpaks.txt}"
SETUP_PKGS_NIXPKGS_FILE="${SETUP_PKGS_NIXPKGS_FILE:-$XDG_DATA_HOME/meta/nixpkgs.txt}"
SETUP_RUNIT_SVHOME="${SETUP_RUNIT_SVHOME:-/etc/sv}"
SETUP_RUNIT_SVDIR="${SETUP_RUNIT_SVDIR:-/var/service}"
SETUP_RUNIT_SVHOME_USER="${SETUP_RUNIT_SVHOME_USER:-${SVHOME_USER:-$XDG_CONFIG_HOME/runit/sv}}"
SETUP_RUNIT_SVDIR_USER="${SETUP_RUNIT_SVDIR_USER:-${SVDIR_USER:-$XDG_DATA_HOME/services}}"

[ -n "${SETUP_BROWSER_DIR:-}" ] || case "$BROWSER" in
zen-browser) SETUP_BROWSER_DIR="$HOME/.zen" ;;
librewolf) SETUP_BROWSER_DIR="$HOME/.librewolf" ;;
waterfox) SETUP_BROWSER_DIR="$HOME/.waterfox" ;;
firefox) SETUP_BROWSER_DIR="$HOME/.mozilla/firefox" ;;
*)
	[ "$1" = "browser" ] || [ "$1" = "install" ] && {
		echo "$(basename "$0"): cannot determine SETUP_BROWSER_DIR" >&2
		exit 1
	}
	;;
esac

# shellcheck disable=SC2015
sudocmd="$([ -f /etc/doas.conf ] && command -v doas 2>/dev/null || command -v sudo 2>/dev/null)"

[ "$(id -u)" -eq 0 ] && {
	echo "$(basename "$0"): this script should not run as root" >&2
	exit 1
}

setup_dotfiles() {
	cp -srfvt "$HOME" "$HERE/.config" "$HERE/.local"
	[ -d "$HOME/.ssh" ] || mkdir -pv "$HOME/.ssh"
	grep -Fxq "Include ~/.config/ssh/config" "$HOME/.ssh/config" ||
		sed -i "1s@^@Include ~/.config/ssh/config\n\n@" "$HOME/.ssh/config"
	[ -d "$HERE/etc" ] &&
		$sudocmd cp --preserve=mode,links,timestamp -rfvt /etc "$HERE/etc/."
	[ -d "$HERE/usr" ] &&
		$sudocmd cp --preserve=mode,links,timestamp -rfvt /usr "$HERE/usr/."
	[ -x /usr/local/bin/pinentry-fuzzel ] &&
		$sudocmd ln -sfv /usr/local/bin/pinentry-fuzzel /usr/bin/pinentry
	[ -n "${WINEPREFIX:-}" ] &&
		command -v wine >/dev/null 2>&1 &&
		mkdir -pv "$WINEPREFIX"
	command -v gsettings >/dev/null 2>&1 && {
		gsettings set org.gnome.desktop.interface color-scheme prefer-dark
		gsettings set org.gnome.desktop.interface gtk-theme "${GTK_THEME:-Adwaita-dark}"
		gsettings set org.gnome.desktop.interface icon-theme Adwaita
		gsettings set org.gnome.desktop.interface cursor-theme "${XCURSOR_THEME:-Adwaita}"
		gsettings set org.gnome.desktop.interface cursor-size "${XCURSOR_SIZE:-24}"
	}
	return 0
}

setup_pkgs() {
	$sudocmd xbps-install -Sy &&
		$sudocmd xbps-install -Suy xbps &&
		$sudocmd xbps-install -Suy
	$sudocmd xbps-install -Sy void-repo-nonfree &&
		$sudocmd xbps-install -Sy
	[ -r "$SETUP_PKGS_FILE" ] &&
		xargs "$sudocmd" xbps-install -Sy <"$SETUP_PKGS_FILE"
	command -v nix >/dev/null 2>&1 && {
		nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
		nix-channel --update
		nix registry pin nixpkgs
		[ -r "$SETUP_PKGS_NIXPKGS_FILE" ] &&
			xargs nix profile add <"$SETUP_PKGS_NIXPKGS_FILE"
	}
	command -v flatpak >/dev/null 2>&1 && {
		flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
		[ -r "$SETUP_PKGS_FLATPAKS_FILE" ] &&
			xargs flatpak install -y <"$SETUP_PKGS_FLATPAKS_FILE"
	}
	command -v go >/dev/null 2>&1 &&
		go telemetry off
	command -v rustup >/dev/null 2>&1 &&
		rustup default stable
	command -v mpv >/dev/null 2>&1 && [ -f /usr/lib/mpv-mpris/mpris.so ] && {
		[ -d /etc/mpv/scripts ] || $sudocmd mkdir -pv /etc/mpv/scripts
		$sudocmd ln -sfvt /etc/mpv/scripts /usr/lib/mpv-mpris/mpris.so
	}
	return 0
}

setup_user() {
	[ -r "$XDG_CONFIG_HOME/user-dirs.dirs" ] && {
		cut -d "=" -f 2 <"$XDG_CONFIG_HOME/user-dirs.dirs" |
			sed -e "s|\$HOME|$HOME|" |
			xargs mkdir -pv
		command -v xdg-user-dirs-update >/dev/null 2>&1 &&
			xdg-user-dirs-update
	}
	chsh -s "$(chsh -l | grep -F -m 1 /zsh)"
	$sudocmd usermod -aG video,audio,input,storage,optical,network,lp,scanner "$USER"
	[ -c /dev/kvm ] &&
		$sudocmd usermod -aG kvm "$USER"
	command -v dbus-daemon >/dev/null 2>&1 &&
		$sudocmd usermod -aG dbus "$USER"
	command -v socklog >/dev/null 2>&1 &&
		$sudocmd usermod -aG socklog "$USER"
	command -v docker >/dev/null 2>&1 &&
		$sudocmd usermod -aG docker "$USER"
	command -v nix >/dev/null 2>&1 &&
		$sudocmd usermod -aG nixbld "$USER"
	return 0
}

setup_runit() {
	$sudocmd rm -vf \
		"$SETUP_RUNIT_SVDIR/agetty-tty4" \
		"$SETUP_RUNIT_SVDIR/agetty-tty5" \
		"$SETUP_RUNIT_SVDIR/agetty-tty6" \
		"$SETUP_RUNIT_SVDIR/acpid" \
		"$SETUP_RUNIT_SVDIR/wpa_supplicant"
	$sudocmd ln -svft "$SETUP_RUNIT_SVDIR" \
		"$SETUP_RUNIT_SVHOME/socklog-unix" \
		"$SETUP_RUNIT_SVHOME/nanoklogd" \
		"$SETUP_RUNIT_SVHOME/udevd" \
		"$SETUP_RUNIT_SVHOME/chronyd" \
		"$SETUP_RUNIT_SVHOME/cronie" \
		"$SETUP_RUNIT_SVHOME/dbus" \
		"$SETUP_RUNIT_SVHOME/rtkit" \
		"$SETUP_RUNIT_SVHOME/elogind" \
		"$SETUP_RUNIT_SVHOME/dhcpcd" \
		"$SETUP_RUNIT_SVHOME/iwd" \
		"$SETUP_RUNIT_SVHOME/bluetoothd" \
		"$SETUP_RUNIT_SVHOME/ufw" \
		"$SETUP_RUNIT_SVHOME/tlp" \
		"$SETUP_RUNIT_SVHOME/sshd" \
		"$SETUP_RUNIT_SVHOME/keyd" \
		"$SETUP_RUNIT_SVHOME/cupsd" \
		"$SETUP_RUNIT_SVHOME/zramen" \
		"$SETUP_RUNIT_SVHOME/nix-daemon" \
		"$SETUP_RUNIT_SVHOME/power-profiles-daemon" \
		"$SETUP_RUNIT_SVHOME/vnstatd"
	[ -d "$SETUP_RUNIT_SVDIR/sshd" ] &&
		$sudocmd touch "$SETUP_RUNIT_SVDIR/sshd/down"
	[ -d "$SETUP_RUNIT_SVHOME_USER" ] && {
		mkdir -pv "$SETUP_RUNIT_SVDIR_USER"
		ln -svft "$SETUP_RUNIT_SVDIR_USER" \
			"$SETUP_RUNIT_SVHOME_USER/foot" \
			"$SETUP_RUNIT_SVHOME_USER/kanshi" \
			"$SETUP_RUNIT_SVHOME_USER/mako" \
			"$SETUP_RUNIT_SVHOME_USER/pipewire" \
			"$SETUP_RUNIT_SVHOME_USER/swayidle" \
			"$SETUP_RUNIT_SVHOME_USER/poweralertd" \
			"$SETUP_RUNIT_SVHOME_USER/cliphist-text" \
			"$SETUP_RUNIT_SVHOME_USER/cliphist-image" \
			"$SETUP_RUNIT_SVHOME_USER/wl-clip-persist" \
			"$SETUP_RUNIT_SVHOME_USER/mpd" \
			"$SETUP_RUNIT_SVHOME_USER/mpdris2-rs" \
			"$SETUP_RUNIT_SVHOME_USER/mpris-proxy" \
			"$SETUP_RUNIT_SVHOME_USER/playerctld" \
			"$SETUP_RUNIT_SVHOME_USER/podman" \
			"$SETUP_RUNIT_SVHOME_USER/syncthing" \
			"$SETUP_RUNIT_SVHOME_USER/waybar" \
			"$SETUP_RUNIT_SVHOME_USER/wbg"
	}
	return 0
}

setup_iw() {
	[ -f /etc/conf.d/wireless-regdom ] && {
		unset WIRELESS_REGDOM
		# shellcheck disable=SC1091
		. /etc/conf.d/wireless-regdom
	}
	[ -n "${WIRELESS_REGDOM:-}" ] && return 0
	[ -e /etc/localtime ] || return 1
	tz="$(readlink -f /etc/localtime)"
	tz="${tz#/usr/share/zoneinfo/}"
	reg="$(grep -m 1 "$tz" /usr/share/zoneinfo/zone.tab | cut -f 1)"
	expr "$reg" : "^[A-Z]\{2\}$" >/dev/null 2>&1 || return 1
	echo "WIRELESS_REGDOM=\"$reg\"" |
		$sudocmd tee -a /etc/conf.d/wireless-regdom >/dev/null
	command -v iw >/dev/null 2>&1 &&
		$sudocmd iw reg set "$reg"

}

setup_ufw() {
	$sudocmd ufw default deny incoming
	$sudocmd ufw default allow outgoing
	$sudocmd ufw limit ssh
	$sudocmd ufw allow in proto udp from 172.16.0.0/12 to 172.17.0.1 port 53 comment "allow-docker-dns"
	$sudocmd ufw --force enable
}

setup_drivers() {
	pkgs=""
	cpu_model="$(grep -i -m 1 "^model name\s:" /proc/cpuinfo)"
	echo "$cpu_model" | grep -iq "intel" && pkgs="$pkgs linux-firmware-intel intel-ucode"
	echo "$cpu_model" | grep -iq "amd" && pkgs="$pkgs linux-firmware-amd"
	gpu_model="$(lspci | grep -i "vga\|3d\|display")"
	echo "$gpu_model" | grep -iq "intel" && {
		pkgs="$pkgs linux-firmware-intel mesa-vulkan-intel"
		echo "$gpu_model" | grep -iq "hd graphics\|xe\|iris" && pkgs="$pkgs intel-media-driver"
		echo "$gpu_model" | grep -Fiq "gma" && pkgs="$pkgs libva-intel-driver"
		[ -e /etc/modprobe.d/i915.conf ] ||
			echo "options i915 enable_guc=2 enable_dc=4 enable_hangcheck=0 error_capture=0 enable_dp_mst=0 fastboot=1" |
			$sudocmd tee /etc/modprobe.d/i915.conf >/dev/null
	}
	echo "$gpu_model" | grep -iq "amd" && {
		pkgs="$pkgs linux-firmware-amd amdvlk ROCm-SMI"
		echo "$gpu_model" | grep -iq "radeon\|amd/ati" && pkgs="$pkgs mesa-vulkan-radeon"
		[ -e /etc/modprobe.d/amdgpu.conf ] ||
			echo "options amdgpu gpu_recovery=1 lockup_timeout=10000 ppfeaturemask=0xffffffff" |
			$sudocmd tee /etc/modprobe.d/amdgpu.conf >/dev/null
	}
	echo "$pkgs" | xargs "$sudocmd" xbps-install -Sy
	xbps-query --regex -p pkgname -s "linux[0-9]+.[0-9]+" |
		cut -d " " -f 2 |
		xargs "$sudocmd" xbps-reconfigure -f
}

setup_browser() {
	[ -d "$SETUP_PROGRAMS_DIR/arkenfox-user.js" ] ||
		git clone https://github.com/arkenfox/user.js.git "$SETUP_PROGRAMS_DIR/arkenfox-user.js"
	git -C "$SETUP_PROGRAMS_DIR/arkenfox-user.js" pull --rebase
	[ -d "$SETUP_BROWSER_DIR" ] || {
		$BROWSER --headless >/dev/null 2>&1 &
		ffpid=$!
		sleep 1
	}
	sed -n "/Default=.*\..*/s/.*=//p" "$SETUP_BROWSER_DIR/profiles.ini" |
		while IFS= read -r p; do
			cp -vf "$SETUP_PROGRAMS_DIR/arkenfox-user.js/user.js" "$SETUP_BROWSER_DIR/$p/user.js"
			browsers="firefox"
			[ "$BROWSER" != "$browsers" ] && browsers="$browsers $BROWSER"
			for b in $browsers; do
				[ -r "$XDG_CONFIG_HOME/$b/user.js" ] &&
					cat "$XDG_CONFIG_HOME/$b/user.js" >>"$SETUP_BROWSER_DIR/$p/user.js"
				[ -d "$XDG_CONFIG_HOME/$b/chrome" ] &&
					cp -rvL "$XDG_CONFIG_HOME/$b/chrome" "$SETUP_BROWSER_DIR/$p"
			done
		done
	[ -n "${ffpid:-}" ] && kill "$ffpid" || true
}

setup_install() {
	setup_dotfiles
	setup_pkgs
	setup_user
	setup_runit
	setup_iw
	setup_ufw
	setup_drivers
	setup_browser
}

setup_uninstall() {
	find "$HERE/.config" "$HERE/.local" -type f |
		while IFS= read -r p; do
			f="${p#"$HERE/"}"
			[ -L "$HOME/$f" ] &&
				[ "$HERE/$f" = "$(readlink -f "$HOME/$f")" ] ||
				continue
			rm -vf "$HOME/$f"
		done
	sed -n "/Default=.*\..*/s/.*=//p" "$SETUP_BROWSER_DIR/profiles.ini" |
		while IFS= read -r p; do
			# shellcheck disable=SC2015
			[ -r "$SETUP_BROWSER_DIR/$p/user.js" ] &&
				cat "$SETUP_PROGRAMS_DIR/arkenfox-user.js/user.js" "$XDG_CONFIG_HOME/firefox/user.js" "$XDG_CONFIG_HOME/$BROWSER/user.js" |
				cmp "$SETUP_BROWSER_DIR/$p/user.js" ||
				continue
			rm -vf "$SETUP_BROWSER_DIR/$p/user.js"
		done
}

case "${1:-dotfiles}" in
install) setup_install ;;
dotfiles) setup_dotfiles ;;
pkgs) setup_pkgs ;;
user) setup_user ;;
runit) setup_runit ;;
iw) setup_iw ;;
ufw) setup_ufw ;;
drivers) setup_drivers ;;
browser) setup_browser ;;
uninstall) setup_uninstall ;;
*)
	echo "$(basename "$0"): unknown command: $1" >&2
	exit 1
	;;
esac
