#!/bin/sh

HERE="$(dirname "$(readlink -f "$0")")"
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
PROGRAMSDIR="${PROGRAMSDIR:-$HOME/programs}"
sudocmd="$(command -v doas 2>/dev/null || command -v sudo 2>/dev/null)"
browserdir="$HOME/.mozilla/firefox"

setupdotfiles() {
	cp -srfv -t "$HOME" "$HERE/.config" "$HERE/.local"
	ln -sfv "$XDG_CONFIG_HOME/shell/profile" "$HOME/.zprofile"
	"$sudocmd" cp -srfv -t /etc/X11 "$XDG_CONFIG_HOME/x11/xorg.conf.d"
	"$sudocmd" cp -srfv -t /etc "$XDG_CONFIG_HOME/acpi" "$XDG_CONFIG_HOME/zzz.d"
	"$sudocmd" cp -fv "$XDG_CONFIG_HOME/doas/doas.conf" /etc/doas.conf
}

setupfirefox() {
	profile="$(sed -n "/Default=.*\..*/s/.*=//p" "$browserdir/profiles.ini")"
	[ -d "$PROGRAMSDIR/arkenfox-user.js" ] || git clone https://github.com/arkenfox/user.js "$PROGRAMSDIR/arkenfox-user.js"
	cat "$PROGRAMSDIR/arkenfox-user.js/user.js" "$XDG_CONFIG_HOME/firefox/user.js" >"$browserdir/$profile/user.js"
}

clean() {
	cd "$HERE" || exit 1
	find .config .local -type f -exec rm -fv "$HOME/{}" \;
	find "$HOME" -maxdepth 1 -xtype l -exec rm -fv "{}" \;
	"$sudocmd" find /etc/X11/xorg.conf.d /etc/acpi /etc/zzz.d -xtype l -exec rm -fv "{}" \;
	profile="$(sed -n "/Default=.*\..*/s/.*=//p" "$browserdir/profiles.ini")"
	[ -s "$browserdir/$profile/user.js" ] && rm -fv "$browserdir/$profile/user.js"
}

case "$1" in
	""|all) setupdotfiles && setupfirefox ;;
	dotfiles) setupdotfiles ;;
	firefox) setupfirefox ;;
	clean) clean ;;
	*)
		echo "$(basename "$0"): unknown command \"$1\"" >&2
		exit 1
		;;
esac
