#!/bin/sh
# vim: wrap

HERE="$(dirname "$(readlink -f "$0")")"
if [ -x "$HERE/setup" ]; then
	echo "running setup dotfiles script..."
	"$HERE/setup" dotfiles
fi

[ -f "$HERE/.config/shell/profile" ] &&
	DISPLAY="${DISPLAY:-:0}" . "$HERE/.config/shell/profile"

PROGRAMSDIR="${PROGRAMSDIR:-$HOME/programs}"
[ -d "$PROGRAMSDIR" ] || mkdir -p "$PROGRAMSDIR"

echo "updating pacman & repos"
sudo pacman -Sy --needed --noconfirm pacman
sudo pacman -Syu --noconfirm

if ! command -v doas >/dev/null 2>&1; then
	echo "installing doas"
	sudo pacman -S --needed --noconfirm opendoas
	echo "permit nopass keepenv :wheel" | sudo tee /etc/doas.conf >/dev/null
fi

alias pacinst="doas pacman -S --needed --noconfirm"
alias yayinst="yay -S --needed --noconfirm --color=auto"

echo "installing base & build tools"
pacinst base base-devel git

echo "installing drivers"
pacinst mesa mesa-utils mesa-vdpau libva-mesa-driver xf86-video-amdgpu vulkan-intel amdvlk intel-ucode

echo "installing xorg & elogind"
pacinst xorg elogind elogind-runit

echo "installing network, firewall & bluetooth"
pacinst networkmanager networkmanager-runit ufw ufw-runit bluez bluez-runit bluez-utils bluez-tools

echo "installing pipewire"
pacinst pipewire pipewire-audio pipewire-pulse wireplumber pulsemixer

if ! command -v yay >/dev/null 2>&1; then
	echo "installing yay"
	cd "$PROGRAMSDIR" || exit 1
	git clone "https://aur.archlinux.org/yay.git" &&
		cd yay && makepkg -si --noconfirm || exit 1
	yay --sudo doas --sudoflags -- --save
fi

echo "installing general tools"
pacinst pacman-contrib xdg-utils xdotool xclip xwallpaper acpilight curl wget rsync gnupg openssh openssh-runit sshfs pass gnome-keyring autofs sysfsutils keepassxc bc slop maim dunst picom xss-lock time entr snooze mlocate nnn fzy fzf ripgrep dust ntp ntp-runit cronie cronie-runit libnotify darkhttpd darkhttpd-runit yt-dlp tar xz gzip bzip2 zstd zip unzip tlp tlp-rdw tlp-runit thermald thermald-runit earlyoom earlyoom-runit highlight redshift newsboat calcurse srm lftp hwinfo firejail zbar qrencode mediainfo atool tree bat git-delta tig rsm clipmenu translate-shell screenkey z duf realtime-privileges wmname gnome-epub-thumbnailer
yayinst xbanish urlview buku-git dragon-drop sc-im bicon-git wiki-tui

echo "installing manual pages"
pacinst man-db man-pages texinfo tealdeer

echo "installing text editor & zsh"
pacinst vim neovim tmux zsh zsh-completions zsh-autosuggestions zsh-history-substring-search
yayinst zsh-fast-syntax-highlighting

echo "installing multimedia tools"
pacinst ffmpeg imagemagick gimp sox mpv nsxiv zathura mupdf zathura-pdf-mupdf zathura-ps zathura-djvu libwebp poppler

echo "installing filesystems support"
pacinst fuse3 exfat-utils mtpfs
yayinst simple-mtpfs

echo "installing music players"
pacinst mpd mpc ncmpcpp

echo "installing email tools"
pacinst neomutt msmtp isync notmuch
yayinst mutt-wizard-git abook

echo "installing programming stuff"
pacinst llvm clang lld tcc nasm zig rustup go python pyenv python-pip python-pipx python-pipenv lua luarocks gdb gef valgrind radare2 delve binutils upx jq cppcheck staticcheck shellcheck tokei hyperfine nix docker docker-compose dive
rustup default stable && cargo install cargo-update cargo-info

echo "installing system monitoring tools"
pacinst socklog perf strace lm_sensors powertop nvtop iotop fio iftop wavemon bandwhich speedtest-cli vnstat vnstat-runit
yayinst htop-vim

echo "installing internet stuff"
pacinst librewolf tor lynx w3m amfora weechat
yayinst arkenfox-user.js
if [ -x "$HERE/setup" ]; then
	echo "running setup librewolf script..."
	librewolf --headless >/dev/null 2>&1 &
	sleep 1
	"$HERE/setup" librewolf
	pkill librewolf
fi

echo "installing torrent tools"
pacinst rtorrent transmission-cli transmission-runit

echo "installing networking tools"
pacinst nmap openbsd-netcat lsof inetutils iputils net-tools ldns traceroute mtr wireshark-cli socat websocat mitmproxy termshark iperf3 arp-scan tcpreplay bettercap macchanger sqlmap gping netsniff-ng aircrack-ng proxychains-ng sslscan urh xh
yayinst wrk nemesis

echo "installing markup & latex"
pacinst pandoc-bin lowdown texlive-core

echo "installing fonts, themes & icons"
pacinst libertinus-font ttf-dejavu ttf-ibm-plex noto-fonts noto-fonts-emoji adwaita-icon-theme
yayinst ttf-amiri adwaita-plus-git nordic-darker-theme

packerdir="${XDG_DATA_HOME:-$HOME/.local/share}/nvim/site/pack/packer/start/packer.nvim"
if [ ! -d "$packerdir" ]; then
	echo "installing packer.nvim"
	git clone --depth 1 "https://github.com/wbthomason/packer.nvim" "$packerdir"
fi

[ -x "$HERE/.local/bin/sysupdate" ] && "$HERE/.local/bin/sysupdate" local
