#!/bin/sh
# vim: wrap

HERE="$(dirname "$(readlink -f "$0")")"
if [ -x "$HERE/setup" ]; then
	echo "running dotfiles setup script..."
	"$HERE/setup"
fi

[ -s "$HERE/.config/shell/profile" ] &&
	DISPLAY="${DISPLAY:-:0}" . "$HERE/.config/shell/profile"

PROGRAMSDIR="${PROGRAMSDIR:-$HOME/programs}"
[ -d "$PROGRAMSDIR" ] || mkdir -p "$PROGRAMSDIR"

echo "updating pacman & repos"
sudo pacman -Sy --needed --noconfirm pacman
sudo pacman -Syu --noconfirm

if ! command -v doas >/dev/null 2>&1; then
	echo "installing doas"
	sudo pacman -S --needed --noconfirm opendoas
	echo "permit nopass keepenv :wheel" | sudo tee /etc/doas.conf >/dev/null
fi

alias pacinst="doas pacman -S --needed --noconfirm"
alias yayinst="yay -S --needed --noconfirm --color=auto"

echo "installing base & build tools"
pacinst base base-devel autofs git

echo "installing drivers"
pacinst libva-mesa-driver mesa-vdpau vulkan-intel vulkan-radeon intel-ucode

echo "installing xorg & elogind"
pacinst xorg elogind elogind-runit

echo "installing network, bluetooth & firewall manager"
pacinst networkmanager networkmanager-runit bluez bluez-runit ufw ufw-runit

echo "installing pipewire"
pacinst pipewire pipewire-audio pipewire-pulse wireplumber pulsemixer

if ! command -v doas >/dev/null 2>&1; then
	echo "installing yay"
	cd "$PROGRAMSDIR" || exit 1
	git clone "https://aur.archlinux.org/yay.git" &&
		cd yay && makepkg -si || exit 1
	yay --sudo doas --sudoflags -- --save
fi

echo "installing general tools"
pacinst pacman-contrib rsm xdg-utils xdotool xdo xclip xsel xwallpaper acpilight curl wget rsync gnupg openssh mosh pass keychain signify keepassxc bc slop maim dunst picom xss-lock time parallel entr snooze mlocate fzy fzf ripgrep dust ntp ntp-runit cronie cronie-runit libnotify darkhttpd darkhttpd-runit youtube-dl yt-dlp tar xz unrar bzip2 zstd gzip zip unzip tlp tlp-rdw tlp-runit thermald thermald-runit highlight redshift newsboat calcurse srm lftp hwinfo firejail zbar qrencode mediainfo atool tree bat git-delta tig clipmenu translate-shell screenkey mdp z duf
yayinst xbanish urlview pam-gnupg spt nnn-nerd buku-git dragon-drop sc-im safeeyes bicon-git wiki-tui

echo "installing manual pages"
pacinst man-db man-pages texinfo tealdeer

echo "installing text editor & zsh"
pacinst vim neovim tmux zsh zsh-completions zsh-autosuggestions zsh-history-substring-search
yayinst zsh-fast-syntax-highlighting

echo "installing multimedia tools"
pacinst ffmpeg imagemagick gimp sox mpv nsxiv zathura mupdf zathura-pdf-mupdf zathura-ps zathura-djvu libwebp poppler

echo "installing music players"
pacinst mpd mpc ncmpcpp

echo "installing email tools"
pacinst neomutt msmtp isync notmuch
yayinst mutt-wizard-git abook

echo "installing programming stuff"
pacinst clang clang lld tcc nasm yasm go rustup zig python pyenv python-pip python-pipx python-pipenv python-nox python-black python-pylint r lua luarocks perl deno nodejs pnpm ruby gdb valgrind binutils upx dive jq jo cppcheck shellcheck shfmt elixir erlang clisp jdk-openjdk clojure leiningen julia kotlin sbt gef postgresql sqlite redis ipython python-numpy python-matplotlib python-scipy jupyterlab jupyter-notebook grpc grpc-cli protobuf terraform radare2 tokei hyperfine bacon stylua android-tools staticcheck delve mono dotnet-sdk aspnet-runtime
yayinst bunjs-bin clib usql tflint-bin flutter android-studio rtx evcxr_jupyter gosec grpcurl
rustup default stable
cargo install cargo-update cargo-info cargo-edit cargo-watch cargo-make irust
go install -v github.com/google/pprof@latest
go install -v google.golang.org/protobuf/cmd/protoc-gen-go@latest
go install -v github.com/timakin/bodyclose@latest

echo "installing system monitoring tools"
pacinst socklog perf strace lm_sensors powertop nvtop iotop fio iftop wavemon bandwhich speedtest-cli vnstat vnstat-runit
yayinst htop-vim

echo "installing internet stuff"
pacinst brave-bin tor lynx w3m amfora weechat

echo "installing torrent tools"
pacinst rtorrent transmission-cli transmission-runit btfs

echo "installing networking tools"
pacinst nmap openbsd-netcat lsof inetutils iputils net-tools traceroute mtr wireshark-cli socat websocat mitmproxy termshark iperf3 arp-scan tcpreplay bettercap macchanger sqlmap gping netsniff-ng aircrack-ng proxychains-ng sslscan urh xh
yayinst wrk nemesis

echo "installing docker"
pacinst docker docker-compose

echo "installing nix"
pacinst nix

echo "installing arduino"
pacinst arduino arduino-cli

echo "installing markup & latex tools"
pacinst pandoc-bin lowdown texlive-basic

echo "installing fonts, themes & icons"
pacinst gnu-free-fonts ttf-liberation ttf-dejavu noto-fonts noto-fonts-emoji adwaita-icon-theme
yayinst otf-ibm-plex ttf-amiri adwaita-dark adwaita-plus-git

PACKERDIR="${PACKERDIR:-${XDG_DATA_HOME:-$HOME/.local/share}/nvim/site/pack/packer/start/packer.nvim}"
if [ ! -f "$PACKERDIR" ]; then
	echo "installing packer.nvim"
	git clone --depth 1 "https://github.com/wbthomason/packer.nvim" "$PACKERDIR"
fi

[ -x "$HERE/.local/bin/sysupdate" ] && "$HERE/.local/bin/sysupdate" local
