#!/bin/sh

# shellcheck disable=2139
alias e="${EDITOR:-vi}"
alias q="exit"

alias mkd="mkdir -pv"
alias cp="cp -iv"
alias ln="ln -iv"
alias mv="mv -iv"
alias rm="rm -Iv"
alias ls="ls -hF --color=auto --group-directories-first"
alias ll="ls -lA"
alias grep="grep --color=auto"
alias gr="grep --exclude-dir={.git,node_modules} -Hnr"

alias g="git"
alias gst="git status -sb"
alias gph="git push"
alias gpl="git pull"
alias gdf="git diff"

alias reboot="loginctl -i reboot"
alias poweroff="loginctl -i poweroff"

alias ip="ip -color=auto"
alias bc="bc -ql"
alias nnn="nnn -Rr"
alias diff="diff --color=auto"
alias info="info --vi-keys"
alias ccat="highlight -O ansi"
alias rsync="rsync -vrPlu"
alias ffmpeg="ffmpeg -hide_banner"
alias urls="grep -aohE '(((http|https|gopher|gemini|ftp|ftps|git)://|www\\.)[a-zA-Z0-9.]*[:;a-zA-Z0-9./+@$&%?$\#=_~-]*)|((magnet:\\?xt=urn:btih:)[a-zA-Z0-9]*)'"
alias bm="buku --suggest"
alias drag="dragon-drop -a -x"
alias adb='env HOME="$ANDROID_USER_HOME" adb'
alias mitmproxy='mitmproxy --set confdir="$XDG_CONFIG_HOME/mitmproxy"'
alias mitmweb='mitmweb --set confdir="$XDG_CONFIG_HOME/mitmproxy"'

pass() {
	case "$EDITOR" in
		vim | nvim) editor="$EDITOR --noplugin" ;;
		*) editor="vi" ;;
	esac
	env EDITOR="$editor" pass "$@"
	unset editor
}

zk() {
	NOTES_DIR="${NOTES_DIR:-$(xdg-user-dir DOCUMENTS)/share/notes}"
	[ ! -d .zk ] && [ -d "$NOTES_DIR" ] && {
		command zk -W "$NOTES_DIR" "$@"
		return $?
	}
	command zk "$@"
}

[ -f "$XINITRC" ] && alias startx='startx "$XINITRC"'
[ -f "$MBSYNCRC" ] && alias mbsync='mbsync -c "$MBSYNCRC"'

# shellcheck disable=2015
sudocmd="$([ -f /etc/doas.conf ] && command -v doas 2>/dev/null || command -v sudo 2>/dev/null)"
for cmd in su mount umount sv vsv ufw; do
	alias $cmd="$sudocmd $(which "$cmd")"
done
unset sudocmd cmd
