#!/bin/sh

alias ls="ls -p --color=auto"
alias ll="ls -alF"
alias la="ls -A"
alias l="ls -CF"

alias grep="grep --color=auto"

alias gst="git status -sb"
alias gph="git push"
alias gpl="git pull"
alias gdf="git diff"

alias xi="doas xbps-install -Sy"
alias xr="doas xbps-remove -R"
alias xq="xbps-query -R"
alias xs="xbps-query -Rs"

alias vi="nvim"
alias x+="chmod +x"
alias cd..="cd .."
