#!/bin/sh

alias e="${EDITOR:-vi}"
alias q="exit"

alias mkd="mkdir -pv"
alias cp="cp -iv"
alias ln="ln -iv"
alias mv="mv -iv"
alias rm="rm -Iv"
alias ls="ls -hF --color=auto --group-directories-first"
alias la="ls -A"
alias ll="ls -lA"
alias grep="grep --color=auto"
alias gr="grep --exclude-dir={.git,node_modules} -Hnr"

alias g="git"
alias gst="git status -sb"
alias gph="git push"
alias gpl="git pull"
alias gdf="git diff"

alias pm="pacman"
alias pacman="pacman --color=auto"
alias yay="yay --color=auto"
alias ip="ip -color=auto"
alias diff="diff --color=auto"
alias ccat="highlight -O ansi"

alias bc="bc -ql"
alias nnn="nnn -Rr"
alias info="info --vi-keys"
alias rsync="rsync -vrPlu"
alias ffmpeg="ffmpeg -hide_banner"
alias ddgr="ddgr -x -n 5 --unsafe --noua"

[ -x "$(command -v nvim 2>/dev/null)" ] && alias vim="nvim" vi="nvim --noplugin" vimdiff="nvim -d"
command -v trash >/dev/null 2>&1 && alias rm="trash"

sudocmd="sudo"
command -v doas >/dev/null 2>&1 && sudocmd="doas"
for cmd in su mount umount updatedb reboot poweroff shutdown sv rsm pacman; do
	alias $cmd="$sudocmd $cmd"
done
unset sudocmd cmd
