#!/bin/sh

set -eu

run() {
	pgrep --quiet --full --euid "$USER" -- "$*" && {
		echo "$(basename "$0"): already running: $*" >&2
		return 0
	}
	"$@" &
}

run pipewire
run keyd-application-mapper
run mpd
run mpris-proxy
run mpdris2-rs --no-notification
run playerctld
run podman --log-level info system service --time 0
run syncthing serve --no-browser

[ "$WAYLAND_DISPLAY" ] && {
	run kanshi
	run swayidle -w
	run foot --server
	run waybar
	run mako
	run poweralertd -s
	run wl-clip-persist --clipboard regular --reconnect-tries 0
	run wl-paste --type text --watch cliphist store
	run wl-paste --type image --watch cliphist store
	run wbg --stretch "${XDG_DATA_HOME:-$HOME/.local/share}/bg"
}
