#!/bin/sh

. "$HOME/.config/shell/env"

doas -n /usr/bin/loadkeys "$XDG_CONFIG_HOME/loadkeys/loadkeysrc"

[ -z "$SSH_AUTH_SOCK" ] && eval "$(ssh-agent -s)"
[ -z "$DBUS_SESSION_BUS_ADDRESS" ] && eval "$(dbus-launch --exit-with-session --sh-syntax)"
dbus-update-activation-environment --all

[ -z "$WAYLAND_DISPLAY" ] && [ "$(tty)" = "/dev/tty1" ] && exec "$XDG_CONFIG_HOME/river/run"
