#!/bin/sh

# shellcheck source=./env
. "${XDG_CONFIG_HOME:-$HOME/.config}/shell/env"

login_file="/tmp/.displaylogin-$USER"
[ -z "${DISPLAY:-${WAYLAND_DISPLAY:-}}" ] &&
	[ "$(tty)" = "/dev/tty1" ] &&
	[ ! -f "$login_file" ] && {
	touch "$login_file"
	exec ssh-agent "$XDG_CONFIG_HOME/river/run"
}
