pulse.rules = [
	{
		matches = [ { application.name = "~Chromium.*" } ]
		actions = { quirks = [ block-source-volume ] }
	}
	{
		matches = [ { application.process.binary = "Discord" } ]
		actions = { quirks = [ block-source-volume ] }
	}
]
