#!/bin/sh

set -eu

case "$(river -version)" in
0.[0-3].*)
	# shellcheck disable=SC1091
	. "$XDG_CONFIG_HOME/river/init-classic"
	;;
*)
	kwm &
	;;
esac

dbus-update-activation-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

command -v runsvdir >/dev/null 2>&1 &&
	! pgrep -x -u "$USER" runsvdir >/dev/null 2>&1 &&
	runsvdir "${SVDIR_USER:-$XDG_DATA_HOME/services}" &
