#!/bin/sh

set -eu

run() { pidof -qsx "$1" || "$@" & }

riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous
riverctl map normal Super+Alt J focus-view -skip-floating next
riverctl map normal Super+Alt K focus-view -skip-floating previous
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

riverctl map -repeat normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map -repeat normal Super L send-layout-cmd rivertile "main-ratio +0.05"
riverctl map -repeat normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map -repeat normal Super+Shift L send-layout-cmd rivertile "main-count -1"

riverctl map -repeat normal Super+Control H move left 100
riverctl map -repeat normal Super+Control J move down 100
riverctl map -repeat normal Super+Control K move up 100
riverctl map -repeat normal Super+Control L move right 100

riverctl map normal Super+Control+Shift H snap left
riverctl map normal Super+Control+Shift J snap down
riverctl map normal Super+Control+Shift K snap up
riverctl map normal Super+Control+Shift L snap right

riverctl map normal Super Space zoom
riverctl map normal Super+Shift C close
riverctl map normal Super F toggle-fullscreen
riverctl map normal Super+Shift Space toggle-float

riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view

riverctl declare-mode passthrough
riverctl map normal Super F11 enter-mode passthrough
riverctl map passthrough Super F11 enter-mode normal

all_tags=$(((1 << 32) - 1))
sticky_tag=$((1 << 31))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags
riverctl map normal Super Tab focus-previous-tags
riverctl map normal Super+Shift Tab send-to-previous-tags
riverctl map normal Super+Shift S toggle-view-tags $sticky_tag
riverctl spawn-tagmask $((all_tags ^ sticky_tag))
for i in 1 2 3 4 5 6 7 8 9; do
	tags=$((1 << (i - 1)))
	riverctl map normal Super "$i" set-focused-tags $((sticky_tag + tags))
	riverctl map normal Super+Shift "$i" set-view-tags $tags
	riverctl map normal Super+Control "$i" toggle-focused-tags $tags
	riverctl map normal Super+Shift+Control "$i" toggle-view-tags $tags
done

riverctl map normal Super Return spawn "$TERMINAL"
riverctl map normal Super R spawn "fuzzel"
riverctl map normal Super Q spawn "menu-sysact"
riverctl map normal None Print spawn "menu-screenshot"
riverctl map normal Alt Print spawn "menu-record"
riverctl map normal Control+Alt Print spawn "menu-record stop"
riverctl map normal Super U spawn "menu-emojis"
riverctl map normal Super I spawn "menu-handler"
riverctl map normal Super O spawn "clipman pick -t CUSTOM -T 'menu -w 60'"
riverctl map normal Super+Shift O spawn "open"
riverctl map normal Super P spawn "passmenu"
riverctl map normal Super+Shift P spawn "passmenu otp"
riverctl map normal Super M spawn "wooz --mouse-track --map-close q"
riverctl map normal Super Backslash spawn "makoctl dismiss -a && pkill -RTMIN+7 waybar"
riverctl map normal Super+Shift Backslash spawn "makoctl mode | grep -Fxq dnd || makoctl dismiss -a; makoctl mode -t dnd && pkill -RTMIN+7 waybar"

for mode in normal locked; do
	riverctl map $mode None XF86Eject spawn "eject -T"

	riverctl map -repeat $mode None XF86AudioRaiseVolume spawn "volumectl 5%+"
	riverctl map -repeat $mode None XF86AudioLowerVolume spawn "volumectl 5%-"
	riverctl map $mode None XF86AudioMute spawn "volumectl toggle"
	riverctl map $mode None XF86AudioMicMute spawn "amixer -q set Capture toggle"
	riverctl map -repeat $mode Super Equal spawn "volumectl 5%+"
	riverctl map -repeat $mode Super Minus spawn "volumectl 5%-"
	riverctl map $mode Super Backspace spawn "volumectl toggle"

	riverctl map $mode None XF86AudioNext spawn "playerctl next"
	riverctl map $mode None XF86AudioPrev spawn "playerctl previous"
	riverctl map $mode None XF86AudioPlay spawn "playerctl play-pause"
	riverctl map $mode None XF86AudioMedia spawn "playerctl play-pause"
	riverctl map $mode Super+Shift Equal spawn "playerctl next"
	riverctl map $mode Super+Shift Minus spawn "playerctl previous"
	riverctl map $mode Super+Shift Backspace spawn "playerctl play-pause"

	riverctl map -repeat $mode None XF86MonBrightnessUp spawn "screenlightctl 10%+"
	riverctl map -repeat $mode None XF86MonBrightnessDown spawn "screenlightctl 10%-"
done

riverctl background-color 0x2e3440
riverctl border-color-urgent 0xb74e58
riverctl border-color-focused 0x5e81ac
riverctl border-color-unfocused 0x4c566a

riverctl rule-add ssd
riverctl rule-add -app-id bar csd
riverctl rule-add -app-id float float
riverctl rule-add -app-id dragon-drop float
riverctl rule-add -title Picture-in-Picture float

riverctl hide-cursor timeout 5000
riverctl hide-cursor when-typing enabled
riverctl set-cursor-warp on-focus-change
riverctl xcursor-theme Adwaita

riverctl set-repeat 50 200
riverctl keyboard-layout -options "caps:escape,grp:alt_space_toggle,grp_led:caps" "us,ara"

riverctl list-inputs | grep -i touchpad | xargs -I{} riverctl input "{}" tap enabled

riverctl default-layout rivertile
rivertile -view-padding 4 -outer-padding 2 &

dbus-update-activation-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

[ -f "$XDG_DATA_HOME/bg" ] && run wbg "$XDG_DATA_HOME/bg"

run foot --server
run kanshi
run pipewire
run mako
run swayidle -w
run poweralertd
run mpris-proxy
run playerctld daemon
run syncthing serve --no-browser
run wl-paste -t text -w clipman store -P --max-items 30
run waybar
# pidof -qsx mpd || (mpd && mpd-mpris) &
