#!/bin/sh

export MOZ_ENABLE_WAYLAND=1
export MOZ_USE_XINPUT2=1
export SDL_VIDEODRIVER="wayland"
export CLUTTER_BACKEND="wayland"
export QT_QPA_PLATFORMTHEME="wayland"
export ECORE_EVAS_ENGINE="wayland-egl"
export ELM_ENGINE="wayland_egl"
export AWT_TOOLKIT="MToolkit wmname LG3D"
export _JAVA_AWT_WM_NOREPARENTING=1
export NO_AT_BRIDGE=1

export XDG_SESSION_TYPE="wayland"
export XDG_SESSION_DESKTOP="river"
export XDG_CURRENT_DESKTOP="river"

[ -z "$DBUS_SESSION_BUS_ADDRESS" ] && eval "$(dbus-launch --exit-with-session --sh-syntax)"
dbus-update-activation-environment --all

exec ssh-agent river -log-level debug >/tmp/river-"$(date "+%F-%T")".log 2>&1
