#!/bin/sh

set -eu

export SDL_VIDEODRIVER="wayland"
export CLUTTER_BACKEND="wayland"
export QT_QPA_PLATFORM="wayland;xcb"
export ELM_DISPLAY="wl"
export MOZ_ENABLE_WAYLAND=1
export NO_AT_BRIDGE=1
export _JAVA_AWT_WM_NONREPARENTING=1
export AWT_TOOLKIT="MToolkit wmname LG3D"

export XDG_SESSION_TYPE="wayland"
export XDG_SESSION_DESKTOP="river"
export XDG_CURRENT_DESKTOP="river"

exec env \
	WLR_BACKENDS="drm,libinput,headless" \
	WLR_HEADLESS_OUTPUTS=1 \
	dbus-run-session river
