#!/bin/sh

set -eu

tag="$1"
appid="scratchpad"

lswt -c a | grep -Fxq "$appid" ||
	riverctl spawn "terminal -a $appid -w 980x620 && riverctl toggle-focused-tags $tag"

riverctl toggle-focused-tags "$tag"

wlrctl window waitfor "app_id:$appid" &&
	wlrctl window focus "app_id:$appid"
