#!/bin/sh

xset -b &
xset r rate 200 50 &
xset s 120 180 &
xss-lock -n "screenlightctl dim" locker &

for p in sxhkd pipewire mpd dunst clipmenud dwmblocks "xbanish -i all"; do
	pidof -qsx "${p%% *}" || $p &
done >/dev/null 2>&1

xbacklight -set 80 &
xrdb "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources"
xwallpaper --zoom "${XDG_DATA_HOME:-$HOME/.local/share}/bg" >/dev/null 2>&1 ||
	xsetroot -solid "$(xrdb -get background)"

exec ssh-agent dwm
