#!/bin/sh

dwmblocks &
mpd &
dunst &
xset r rate 300 50 &
unclutter -noevents &
[ -f "$HOME/.local/share/bg" ] && xwallpaper --zoom "$HOME/.local/share/bg" &

! pidof -s pulseaudio >/dev/null 2>&1 && setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1
