#!/bin/sh

while read -r f; do
	case "$1" in
		w) xwallpaper --zoom "$f" & ;;
		W) wal -i "$f" >/dev/null 2>&1 & ;;
		r) convert -rotate 90 "$f" "$f" ;;
		R) convert -rotate -90 "$f" "$f" ;;
		f) convert -flop "$f" "$f" ;;
		i) notify-send "file info" "$(mediainfo "$f" | sed "s/[ ]\+:/:/g;s/: /: <b>/;s/$/<\/b>/" | grep "<b>")" & ;;
		d) [ "$(printf "no\nyes" | dmenu -i -p "delete $f?")" = "yes" ] && rm "$f" && notify-send "$f deleted" & ;;
		D) rm "$f" && notify-send "$f deleted" & ;;
		y) printf "%s" "$f" | tr -d "\n" | xclip -sel clip && notify-send "$f copied to clipboard" & ;;
		Y) rf="$(readlink -f "$f")"; printf "%s" "$rf" | tr -d "\n" | xclip -sel clip && notify-send "$rf copied to clipboard" & ;;
		g) dragon -x "$f" ;;
	esac
done
