{
    inputs,
    pkgs,
    lib,
    config,
    systemInfo,
    ...
}:
let
    hm = config.home-manager.users.${systemInfo.user};
in
{
    imports = [
        ./hardware.nix
        ./file-system.nix
        ./boot.nix
        ./packages.nix
    ];

    networking.hostName = systemInfo.host;
    system.stateVersion = systemInfo.stateVersion;

    services.logind = {
        enable = true;
        settings = {
            Login = {
                HandlePowerKey = "ignore";
                HandleLidSwitchDocked = "ignore";
            };
        };
    };

    services.udev = {
        enable = true;
        extraRules = ''
            # IO Scheduler
            # HDD
            ACTION=="add|change", KERNEL=="sd[a-z]*", ATTR{queue/rotational}=="1", ATTR{queue/scheduler}="bfq"
            # SSD
            ACTION=="add|change", KERNEL=="sd[a-z]*|mmcblk[0-9]*", ATTR{queue/rotational}=="0", ATTR{queue/scheduler}="bfq"
            # NVMe SSD
            ACTION=="add|change", KERNEL=="nvme[0-9]*", ENV{DEVTYPE}=="disk", ATTR{queue/scheduler}="none"
        '';
    };

    services.keyd.keyboards.redragon-k613 = lib.mkIf config.services.keyd.enable {
        ids = [ "258a:002a" ];
        settings = lib.recursiveUpdate config.services.keyd.keyboards.default.settings {
            main = {
                esc = "`";
            };
        };
    };

    hardware.bluetooth.enable = true;

    networking = {
        wireless.enable = true;
        firewall = {
            # TODO: enable Docker DNS.
            allowedTCPPorts = [
                22000 # Syncthing TCP sync
                53317 # LocalSend TCP transfer
            ];
            allowedUDPPorts = [
                22000 # Syncthing QUIC sync
                21027 # Syncthing discovery
                53317 # LocalSend UDP discovery
            ];
        };
    };

    services.printing = {
        enable = true;
        package = pkgs.cups;
    };

    security.polkit = {
        enable = true;
        package = pkgs.polkit;
    };

    services.power-profiles-daemon = {
        enable = true;
        package = pkgs.power-profiles-daemon;
    };

    programs.dconf.enable = true;
    documentation.dev.enable = true;
    security.pam.services.swaylock = lib.mkIf hm.programs.swaylock.enable { };
    services.gnome.gnome-keyring.enable = true;

    programs.zsh = {
        enable = true;
        enableGlobalCompInit = false;
    };

    environment.pathsToLink = [
        "/share/applications"
        "/share/xdg-desktop-portal"
    ]
    ++ lib.optional config.programs.zsh.enable "/share/zsh";

    users = {
        users.${systemInfo.user} = {
            isNormalUser = true;
            shell = lib.mkIf config.programs.zsh.enable pkgs.zsh;
            extraGroups = [
                "wheel"
                "video"
                "audio"
                "dialout"
                "lp"
                "kvm"
                "networkmanager"
            ]
            ++ lib.optional config.services.keyd.enable "keyd"
            ++ lib.optional config.virtualisation.docker.enable "docker";
        };
        groups.${systemInfo.user} = { };
    };

    home-manager = {
        useGlobalPkgs = true;
        useUserPackages = true;
        extraSpecialArgs = { inherit inputs systemInfo; };
        users.${systemInfo.user} = { ... }: {
            imports = [
                ./../../modules/home
            ];
            home = {
                username = systemInfo.user;
                homeDirectory = "/home/${systemInfo.user}";
                stateVersion = systemInfo.stateVersion;
            };
        };
    };

    # TODO: find a better way to load user environment variables instead of
    # relaying on `~/.profile` (generated by the bash home-manager module).
    services.greetd = {
        enable = true;
        package = pkgs.greetd;
        settings = {
            default_session = {
                user = "greeter";
                command = "${pkgs.dbus}/bin/dbus-run-session ${pkgs.cage}/bin/cage -- ${pkgs.regreet}/bin/regreet";
            };
        };
    };

    programs.regreet = {
        enable = true;
        package = pkgs.regreet;
        font = {
            package = hm.gtk.font.package;
            name = hm.gtk.font.name;
            size = hm.gtk.font.size;
        };
        theme = {
            package = hm.gtk.theme.package;
            name = hm.gtk.theme.name;
        };
        iconTheme = {
            package = hm.gtk.iconTheme.package;
            name = hm.gtk.iconTheme.name;
        };
        cursorTheme = {
            package = hm.gtk.cursorTheme.package;
            name = hm.gtk.cursorTheme.name;
        };
        settings = {
            background = {
                path = "${hm.xdg.dataHome}/bg";
                fit = "Cover";
            };
            GTK = {
                cursor_blink = false;
            };
        };
    };

    programs.mango = {
        enable = true;
        addLoginEntry = true;
    };
}
