{
    inputs,
    pkgs,
    lib,
    config,
    custom,
    ...
}:
{
    imports = [
        ./hardware.nix
        ./file-system.nix
        ./boot.nix
        ./packages.nix
    ];

    networking.hostName = custom.systemInfo.host;
    system.stateVersion = custom.systemInfo.stateVersion;

    home-manager = {
        useGlobalPkgs = true;
        useUserPackages = true;
        extraSpecialArgs = { inherit inputs custom; };
        users.${custom.systemInfo.user} = ./../../modules/home;
    };

    services.logind = {
        enable = true;
        settings = {
            Login = {
                HandlePowerKey = "ignore";
                HandleLidSwitchDocked = "ignore";
            };
        };
    };

    services.udev = {
        enable = true;
        extraRules = ''
            # IO Scheduler
            # HDD
            ACTION=="add|change", KERNEL=="sd[a-z]*", ATTR{queue/rotational}=="1", ATTR{queue/scheduler}="bfq"
            # SSD
            ACTION=="add|change", KERNEL=="sd[a-z]*|mmcblk[0-9]*", ATTR{queue/rotational}=="0", ATTR{queue/scheduler}="bfq"
            # NVMe SSD
            ACTION=="add|change", KERNEL=="nvme[0-9]*", ENV{DEVTYPE}=="disk", ATTR{queue/scheduler}="none"
        '';
    };

    services.keyd.keyboards.redragon-k613 = lib.mkIf config.services.keyd.enable {
        ids = [ "258a:002a" ];
        settings = lib.recursiveUpdate config.services.keyd.keyboards.default.settings {
            main = {
                esc = "`";
            };
        };
    };

    networking = {
        wireless.enable = true;
        firewall = {
            # TODO: enable Docker DNS.
            allowedTCPPorts = [
                22000 # Syncthing TCP sync
                53317 # LocalSend TCP transfer
            ];
            allowedUDPPorts = [
                22000 # Syncthing QUIC sync
                21027 # Syncthing discovery
                53317 # LocalSend UDP discovery
            ];
        };
    };

    services.printing = {
        enable = true;
        package = pkgs.cups;
    };

    security.polkit = {
        enable = true;
        package = pkgs.polkit;
    };

    services.power-profiles-daemon = {
        enable = true;
        package = pkgs.power-profiles-daemon;
    };

    programs.dconf.enable = true;
    documentation.dev.enable = true;

    security.pam.services.swaylock = { };
    services.gnome.gnome-keyring.enable = true;

    programs.nix-ld = {
        enable = true;
        package = pkgs.nix-ld;
    };

    programs.nix-index = {
        enable = true;
        package = pkgs.nix-index;
    };

    programs.zsh = {
        enable = true;
        enableGlobalCompInit = false;
    };

    users = {
        users.${custom.systemInfo.user} = {
            isNormalUser = true;
            shell =
                if config.programs.zsh.enable then
                    config.programs.zsh.package or pkgs.zsh
                else
                    config.programs.bash.package or pkgs.bashInteractive;
            extraGroups = [
                "wheel"
                "video"
                "audio"
                "dialout"
                "lp"
                "kvm"
                "networkmanager"
            ];
        };
        groups.${custom.systemInfo.user} = { };
    };

    # TODO: find a better way to load user environment variables instead of
    # relaying on `~/.profile` (generated by the bash home-manager module).
    services.greetd = {
        enable = true;
        package = pkgs.greetd;
        settings = {
            default_session = {
                user = "greeter";
                command = "${pkgs.tuigreet}/bin/tuigreet --sessions ${config.services.displayManager.sessionData.desktops}/share/xsessions:${config.services.displayManager.sessionData.desktops}/share/wayland-sessions --remember --remember-user-session";
            };
        };
    };

    programs.mango = {
        enable = true;
        addLoginEntry = true;
    };
}
