#!/bin/sh

set -eu

export MENU_PROMPT="${MENU_PROMPT:-Emojis}"

uni emoji all -raw -compact -format "%(emoji)%(tab)%(name)%(cldr_full Q:;[:])" |
	menu --nth-delimiter ";" --with-nth 1 --accept-nth 1 |
	cut -d " " -f 1 |
	wl-copy --type text/plain --foreground --trim-newline
