#!/bin/sh

for xrd in /run/user/*; do
	uid="${xrd##*/}"
	user="$(id -un "$uid")"
	[ -n "$user" ] || {
		echo "failed to find user of $xrd" >&2
		exit 1
	}
	for f in "$xrd"/*; do
		case "$f" in
		*/wayland-[0-9])
			display="${f##*/}"
			break
			;;
		esac
	done
done
[ -n "$display" ] || {
	echo "no session found" >&2
	exit 1
}

home="$(getent passwd "$user" | cut -d ":" -f 6)"
# shellcheck disable=SC2015
[ -n "$home" ] && [ -d "$home" ] ||
	{
		echo "failed to find user $user home directory" >&2
		exit 1
	}

lockcmd="waylock"
[ -x "$home/.local/bin/screenlocker" ] && lockcmd="$home/.local/bin/screenlocker"

exec chpst \
	-u "$user" \
	env USER="$user" HOME="$home" WAYLAND_DISPLAY="$display" XDG_RUNTIME_DIR="$xrd" \
	timeout 5s \
	"$lockcmd"
