#!/bin/sh

set -eu

# pkgname="$1"
# version="$2"

CMDLINE="rw quiet splash apparmor=1 security=apparmor zswap.enabled=0"
BOOT_DIR="/boot"
BOOT_EFI="EFI/BOOT"

EFI_BOOT_DIR="$BOOT_DIR/$BOOT_EFI"
[ -d "$EFI_BOOT_DIR" ] || mkdir -p "$EFI_BOOT_DIR"

root_info="$(findmnt -nvo SOURCE,FSTYPE /)"
root_device="${root_info% *}"
root_fstype="${root_info#* }"
root_uuid="$(blkid -o value -s UUID "$root_device")"

CMDLINE="$CMDLINE root=UUID=$root_uuid rootfstype=$root_fstype"

luks_device="$(lsblk -spJ | jq -r --arg dev "$root_device" '.blockdevices | .[] | select(.name == $dev) | .children | .[0] | .name')"
cryptsetup isLuks "$luks_device" && {
	luks_uuid="$(blkid -o value -s UUID "$luks_device")"
	CMDLINE="$CMDLINE rd.auto rd.luks.allow-discards rd.luks.uuid=luks-$luks_uuid rd.luks.name=$luks_uuid=${root_device##*/}"
}

case "$(getconf LONG_BIT)" in
	32) efi_file="BOOTIA32.EFI" ;;
	64) efi_file="BOOTX64.EFI" ;;
esac

cp -f "/usr/share/limine/$efi_file" "$EFI_BOOT_DIR"

[ -f /boot/limine.conf ] && mv /boot/limine.conf /boot/limine.conf.bak
cp -f /etc/limine/limine.conf /boot/limine.conf

limine_conf="$(
	cat <<-_EOF

		/+Void Linux
		comment: Void Linux
	_EOF
)"

order=50
for version in $(xbps-query --regex -p pkgname -s "linux[0-9]+.[0-9]+" | sed "s/.*-\(.*\):.*/\1/" | sort -nr); do
	kernel_name="vmlinuz-$version"
	ramfs_name="initramfs-$version.img"
	[ -f "$BOOT_DIR/$kernel_name" ] &&
		[ -f "$BOOT_DIR/$ramfs_name" ] ||
		continue
	kernel_hash="$(b2sum "$BOOT_DIR/$kernel_name")"
	kernel_hash="${kernel_hash%% *}"
	ramfs_hash="$(b2sum "$BOOT_DIR/$ramfs_name")"
	ramfs_hash="${ramfs_hash%% *}"
	limine_conf="$(
		cat <<-_EOF
			$limine_conf
			//Linux ${version%.*}
			comment: Kernel version: $version
			comment: order-priority=$order
			protocol: linux
			cmdline: $CMDLINE
			path: boot():/$kernel_name#$kernel_hash
			module_path: boot():/$ramfs_name#$ramfs_hash
		_EOF
	)"
	order=$((order - 1))
done

[ -f /boot/memtest86+/memtest.efi ] &&
	limine_conf="$(
		cat <<-_EOF
			$limine_conf

			/Memtest86+
			comment: Memtest86+
			comment: order-priority=20
			protocol: efi
			path: boot():/memtest86+/memtest.efi
		_EOF
	)"

limine_conf="$(
	cat <<-_EOF
		$limine_conf

		/EFI
		comment: Default EFI loader
		comment: order-priority=10
		protocol: efi
		path: boot():/$BOOT_EFI/$efi_file
	_EOF
)"

echo "$limine_conf" >>/boot/limine.conf
